### ISSUE TITLE
Behance Test

### ISSUE THREAD

**Issue by JohnYangSam** [SiliconValleyInsight/sitbot#2]
Try sitbot on this url:

http://on.be.net/1PqzRXt

seems to turn up an empty sheet on my end.

**Comment by benigeri** [comment]
Stint only works on people searches. Right now, you are searching for projects. 

Ex url: https://www.behance.net/search?field=132&content=users&sort=appreciations&time=week&location_id=26150791-en&country=UA&city=Lviv
